"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const club_controller_1 = require("./../../controller/club.controller");
const express_1 = __importDefault(require("express"));
const asyncHandler_1 = require("../../helper/asyncHandler");
const authUtils_1 = require("../../auth/authUtils");
const rbac_1 = require("../../middleware/rbac");
const router = express_1.default.Router();
router.get('/location', (0, asyncHandler_1.asyncHandler)(club_controller_1.ClubController.getInstance().searchClub));
router.get('/id/:clubId?', (0, asyncHandler_1.asyncHandler)(club_controller_1.ClubController.getInstance().getSlotInfoByClubIdAndDate));
router.get('/:clubId', (0, asyncHandler_1.asyncHandler)(club_controller_1.ClubController.getInstance().findClub));
router.get('/', (0, asyncHandler_1.asyncHandler)(club_controller_1.ClubController.getInstance().getClubs));
router.use(authUtils_1.authentication);
router.post('/', (0, rbac_1.grantAccess)('createOwn', 'club'), (0, asyncHandler_1.asyncHandler)(club_controller_1.ClubController.getInstance().createClub));
router.use(authUtils_1.CheckApiKey);
router.post('/:id', (0, rbac_1.grantAccess)('updateOwn', 'club'), (0, asyncHandler_1.asyncHandler)(club_controller_1.ClubController.getInstance().updateClub));
router.delete('/:id', (0, rbac_1.grantAccess)('deleteOwn', 'club'), (0, asyncHandler_1.asyncHandler)(club_controller_1.ClubController.getInstance().deleteClub));
module.exports = router;
