"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const router = express_1.default.Router();
router.use('/api/roles', require('./role'));
router.use('/api/users', require('./user'));
router.use('/api/auth', require('./auth'));
router.use('/api/clubs', require('./club'));
router.use('/api/courts', require('./court'));
router.use('/api/subscriptionForClubs', require('./subscriptionForClub'));
router.use('/api/clubSubscriptions', require('./clubSubscription'));
router.use('/api/subscriptions', require('./subscription'));
router.use('/api/memberSubscriptions', require('./memberSubscription'));
router.use('/api/payments', require('./payment'));
router.use('/api/reviews', require('./review'));
router.use('/api/slots', require('./slot'));
router.use('/api/staffProfiles', require('./staffProfile'));
router.use('/api/clubImages', require('./clubImage'));
router.use('/api/bookSlots', require('./bookSlot'));
module.exports = router;
